version: "3"

services:
  myapp-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  server:
    image: springboot-container
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myapp-mysql:3306/MyAppDb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "myapp-user"
      SPRING_DATASOURCE_PASSWORD: "password"

  client:
    image: react-container
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    restart: on-failure
    ports:
      - 3000:3000
