version: "3"

services:
  myapp-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Password
    ports:
      - 3306:3306

  myapp-main:
    # image: myapp-image-name-that-appears-when-you-run-docker-images
    build: ./backend
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
